project:
  type: website

website:
  title: "Corballis Lab"
  navbar:
    left:
      - text: "Team"
        file: pages_content/people.qmd
      - text: "Pubblications"
      - text: "Contact Us"
        file: pages_content/contact_us.qmd


format:
  html:
    theme: 
      light: simplex
      dark: [simplex, simplex_dark.sass]
    css: styles.css
    toc: true

editor: visual

